[project]
name = "container-irrexplorer"
version = "1.1"
description = "IRRexplorer"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "poetry==2.1.3",
    "python-dotenv==1.2.1",
]
